### ISSUE TITLE
Does not work with ChartJS >= 3.5

### ISSUE THREAD

**Issue by votdev** [kurkle/chartjs-chart-treemap#49]
The following PR in ChartJS makes the treemap plugin incompatible to the latest version.

- https://github.com/chartjs/Chart.js/pull/9432
- https://github.com/chartjs/Chart.js/commit/8008488aba0a34527e1848e7b4d2e9a73c751885#diff-762f5209048a0efa96ee202a2994ce9d55790766b8fed0a44271b4766c0ab647

```
Error: node_modules/chart.js/types/index.esm.d.ts:452:25 - error TS2536: Type '"metaExtensions"' cannot be used to index type 'ChartTypeRegistry[key]'.

452   { [key in ChartType]: ChartTypeRegistry[key]['metaExtensions'] }[TType]
```
